FROM centos:centos7
RUN yum install -y --nogpgcheck make\
                                cmake\
                                gcc\
                                gcc-c++\
                                boost-devel